### ISSUE TITLE
Long Press to Paste

### ISSUE THREAD

**Issue by oonn22** [oonn22/Cryptocurrency-Wallet#1]
Implement a long press to paste for the recipient field of the main wallet screen. Update placeholder text to describe this feature.

**Comment by MorenoF83** [comment]
Looked through possibilities of the long press, but can't apply it on current design
**Need to change the layout of input to put the functionality**

**Comment by oonn22** [comment]
https://reactnative.dev/docs/handling-touches

See docs above. You can wrap the input in a touchable which has a onLongPress event that can be set to a function that gets text from the clipboard and sets the state of the recipient input to this text.  You may need to set the text property of the input to equal the state variable that stores the recipient input to see the change.

See clipboard docs here: https://docs.expo.dev/versions/latest/sdk/clipboard/
